import { Router } from "express";
import chartAccount from "./chartAccounts.routes";
import dailyBookrutes from "./dailyBook.routes";
import dailyBooksDetailsRoutes from "./dailyBookDetails.routes";
import mayozacionRoutes from "./mayorizacion.routes";
const router: Router = Router();
router.use("/api", dailyBookrutes);
router.use("/api", chartAccount);
router.use("/api", dailyBooksDetailsRoutes);
router.use("/api", mayozacionRoutes);
export default router;
